### ISSUE TITLE
more whitespace cleanup

### ISSUE THREAD

**Issue by thorade** [dietmarw/trimtrailingwhitespaces#35]
Some more ideas for optional whitespace cleanup:
- replace `␣=␣␣` with `␣=␣` until no further occurences found (clean right)
- replace `␣␣=␣` with `␣=␣` until no further occurences found (clean left)
- replace multiple empty lines with single empty line until no further occurences found

These might be intentional, so removing them should be optional. 
Maybe even one option for each?

Or assign names to the rules, like it is done in pep8 and friends?
http://pep8.readthedocs.io/en/stable/intro.html#error-codes

**Comment by dietmarw** [comment]
Sounds like a good idea. Though I won't be able to implement it in the near future. PR welcome ;-)

**Comment by thorade** [comment]
Closing for now, maybe reopen in the future.
https://github.com/modelica/ModelicaStandardLibrary/issues/2931
