### ISSUE TITLE
Add option to remove more than one empty line from code

### ISSUE THREAD

**Issue by christiankral** [dietmarw/trimtrailingwhitespaces#39]
In order to cleanup Modelica code it were also helpful to have an additional option to remove more than one empty line. Such empty consecutive lines are often introduced by Dymola when splitting libraries into single files. However, I think it makes sense to keep single empty lines to structure code, but I cannot think of any case where more than one empty line make sense in Modelica (and HTML) code. 

Certainly, one could always adapt some code snippets provided by https://unix.stackexchange.com/questions/72739/how-to-remove-multiple-blank-lines-from-a-file but having everything needed in one tool were nice :-)

**Comment by dietmarw** [comment]
I also thought about that some years back but discovered that `cat -s` does exactly that and also much faster than ttws could do it. And following the UNIX philosophy
> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

I decided against including this into ttws. 

On Linux a simple:
```sh
$ for fn in `find -name "*.mo"`; do cat -s $fn >$fn.1; mv $fn.1 $fn; done
```
will take care of all .mo files recursively.

**Comment by dietmarw** [comment]
One option could of course be added to shell out to run that command.

**Comment by dietmarw** [comment]
I'll upload a new version with a `--blanks` option later today.
